version: '3'

services:
  application:
    restart: on-failure                     # 실패시에만 컨테이너 재시작
    image: js1171/montaa:latest
    build:
      context: ./                           # 현재 디렉토리('./')에서 Dockerfile 찾아 이미지 빌드
      dockerfile: Dockerfile
    environment:                            # springboot application의 데이터 소스 설정을 위한 환경 변수 설정
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
