name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-database.yml
        run:
          cd ./src/main/resources;
          touch ./application-database.yml;
          echo "${{secrets.DATABASE}}" >> ./application-database.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Compose Services
        run: docker-compose build --no-cache

      - name: Push Docker Compose Images
        run: docker-compose push

      # docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{secrets.KEY}}
          script: |
            cd monta-spring/src/main;
            mkdir resources;
            cd resources;
            touch ./application.yml;
            echo "${{secrets.APPLICATION}}" >> ./application.yml;
            touch ./application-database.yml;
            echo "${{secrets.DATABASE}}" >> ./application-database.yml;
            cd ../../../;
  
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }};
            sudo docker rm -f $(docker ps -qa);
            sudo docker-compose pull;
            sudo docker-compose up -d;
            sudo docker image prune -f