name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-database.yml
        run:
          cd ./src/main/resources;
          touch ./application-database.yml;
          echo "${{secrets.DATABASE}}" >> ./application-database.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Compose Services
        run: docker-compose build --no-cache

      - name: Push Docker Compose Images
        run: docker-compose push

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu"

      - name: Copy nginx/default.conf to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: "./nginx/conf.d/default.conf"
          target: "/home/ubuntu/nginx/conf.d"

      - name: Copy certbot/init-letsencrypt.sh to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: "./certbot/init-letsencrypt.sh"
          target: "/home/ubuntu/certbot"

      # docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{secrets.KEY}}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }};
            sudo docker rm -f $(docker ps -qa);
            sudo docker pull js1171/monta:latest;
            sudo docker-compose up -d;
            sudo docker image prune -f