name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: make application-database.yml
        run:
          cd ./src/main/resources;
          touch ./application-database.yml;
          echo "${{secrets.DATABASE}}" >> ./application-database.yml
        shell: bash
      - name: Build with Gradle
        run: ./gradlew bootJar
      #      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      #      with:
      #        arguments: build
      - name: web docker build and push
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }};
          docker build -t ${{secrets.DOCKER_REPO}}/monta .;      
          docker push ${{secrets.DOCKER_REPO}}/monta
      # docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ubuntu
          key: ${{secrets.KEY}}
          script: |
            sudo docker rm -f $(docker ps -qa);
            sudo docker pull ${{secrets.DOCKER_REPO}}/second-eyes-web;
            sudo docker pull ${{secrets.DOCKER_REPO}}/second-eyes-nginx;
            docker-compose up -d;
            docker image prune -f